export const PLATFORMS = [
  { name: 'DVD', platformConstructor: 'Various' },
  { name: 'Blu-Ray', platformConstructor: 'Various' },
  { name: 'Blu-Ray 4K', platformConstructor: 'Various' },
  { name: 'PlayStation', platformConstructor: 'Sony' },
  { name: 'PlayStation 2', platformConstructor: 'Sony' },
  { name: 'PlayStation 3', platformConstructor: 'Sony' },
  { name: 'PlayStation 4', platformConstructor: 'Sony' },
  { name: 'PlayStation 5', platformConstructor: 'Sony' },
  { name: 'PSP', platformConstructor: 'Sony' },
  { name: 'PlayStation Vita', platformConstructor: 'Sony' },
  {
    name: 'Nintendo Entertainment System',
    platformConstructor: 'Nintendo',
  },
  { name: 'Super Nintendo', platformConstructor: 'Nintendo' },
  { name: 'Nintendo 64', platformConstructor: 'Nintendo' },
  { name: 'GameCube', platformConstructor: 'Nintendo' },
  { name: 'Wii', platformConstructor: 'Nintendo' },
  { name: 'Wii U', platformConstructor: 'Nintendo' },
  { name: 'Switch', platformConstructor: 'Nintendo' },
  { name: 'Game Boy', platformConstructor: 'Nintendo' },
  { name: 'Game Boy Advance', platformConstructor: 'Nintendo' },
  { name: 'Nintendo DS', platformConstructor: 'Nintendo' },
  { name: 'Nintendo 3DS', platformConstructor: 'Nintendo' },
  { name: 'Xbox', platformConstructor: 'Microsoft' },
  { name: 'Xbox 360', platformConstructor: 'Microsoft' },
  { name: 'Xbox One', platformConstructor: 'Microsoft' },
  { name: 'Xbox Series X', platformConstructor: 'Microsoft' },
  { name: 'Master System', platformConstructor: 'Sega' },
  { name: 'Genesis', platformConstructor: 'Sega' },
  { name: 'Sega CD', platformConstructor: 'Sega' },
  { name: '32X', platformConstructor: 'Sega' },
  { name: 'Saturn', platformConstructor: 'Sega' },
  { name: 'Dreamcast', platformConstructor: 'Sega' },
  { name: 'Game Gear', platformConstructor: 'Sega' },
  { name: 'Lynx', platformConstructor: 'Atari' },
  { name: 'Jaguar', platformConstructor: 'Atari' },
];
